#include <iostream>
#include <vector>
using namespace std;

int main() {

    // Read the sequence
    long long N;
    cin >> N;
    vector<long long> sequence(N);
    for (auto &element : sequence) {
        cin >> element;
    }

    // Calculate the total sum of the sequence
    long long totalSum = 0;
    for (auto element : sequence) {
        totalSum += element;
    }

    // Read the target
    long long X;
    cin >> X;

    // Calculate the number of blocks
    long long blocks = X / totalSum;

    // Calculate the remaining target
    long long remainingTarget = X - blocks * totalSum;

    // Find the index where the sum exceeds the target
    long long currentSum = 0;
    for (int i = 0; i < N; i++) {
        currentSum += sequence[i];
        if (currentSum > remainingTarget) {
            cout << i + 1 + blocks * N << endl;
            return 0;
        }
    }
}



/*
    .cph file
{
    "name":"C - Long Sequence",
    "group":"AtCoder - AtCoder Beginner Contest 220",
    "url":"https://atcoder.jp/contests/abc220/tasks/abc220_c",
    "interactive":false,"memoryLimit":1024,"timeLimit":2000,
    "tests":[{"input":"3\n3 5 2\n26\n","output":"8\n","id":1724374303236},{"input":"4\n12 34 56 78\n1000\n","output":"23\n","id":1724374303257}],
    "testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"CLongSequence"}},
    "batch":{"id":"8db8d258-2cf0-4512-8f90-a5060703e1ae","size":1},"srcPath":"d:\\C++\\AtCoder\\AtCoder-Solutions\\C_Long_Sequence.cpp"
}

    // The code documentation and variable renaming were generated by an AI for better readability.

*/